-- This migration has been superseded by 20260701120000_production_schema.sql
-- Kept as a placeholder to preserve migration history ordering.
-- All tables, RLS, and indexes are defined in the production schema above.
